apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logsight.fullname" . }}
  labels:
    {{- include "logsight.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "logsight.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "logsight.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "logsight.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy

          env:
            {{- range .Values.extraEnvs }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
          envFrom:
            - configMapRef:
               name: {{ .Chart.Name }}-config
            - secretRef:
                name: {{ .Chart.Name }}-secrets
            - configMapRef:
                name: service-config
            - secretRef:
                name: service-secrets
          ports:
            - name: log-stream
              containerPort: {{ .Values.service.port }}
              protocol: TCP
{{/*          readinessProbe:*/}}
{{/*            tcpSocket:*/}}
{{/*              port: {{ .Values.service.port }}*/}}
{{/*            initialDelaySeconds: 5*/}}
{{/*            periodSeconds: 10*/}}
{{/*          livenessProbe:*/}}
{{/*            tcpSocket:*/}}
{{/*              port: {{ .Values.service.port }}*/}}
{{/*            initialDelaySeconds: 15*/}}
{{/*            periodSeconds: 20*/}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
