apiVersion: v2
name: logsight-frontend
description: Logsight infuses deep learning and AI-powered analytics to enable continuous software delivery and proactive troubleshooting.
type: application

version: 0.1.1
appVersion: "v1.2.1"
keywords:
  - logs
  - analytics

home: https://logsight.ai
icon: https://logsight.ai/assets/img/logo-logsight.svg

maintainers:
  - name: petar-ilijevski-logsight
    email: petar.ilijevski@logsight.ai
